### ISSUE TITLE
GUI 구성 코드 가독성 최적화가 필요함

### ISSUE THREAD

**Issue by mokminsu** [ujari/PDF_Transducer#1]
## 문제점
GUI 구성 코드들이 무분별하게 삽입 되어 있어 추후 가독성 및 유지보수에 문제가 생길 가능성이 존재함

## 예상 해결 방안
로직과 GUI 구성 코드를 파일 분리 또는 라인 분리가 필요함

**Comment by yoonhoc** [comment]
의견 감사드립니다.^^~
빠른 시일내로 보완하도록 하겠습니다.

Thank you for your opinion. ^^~

I will try to make up for it as soon as possible.
